// kuis-soal.js — bank soal Kuis Crypto Hanif Dossier.
//
// Berkas ini hanya berisi DATA: daftar level (jalur belajar) dan soal-soalnya.
// Logika permainan ada di kuis.html. Dipisah supaya menambah soal tidak perlu
// menyentuh kode permainan sama sekali.
//
// Aturan menulis soal:
//   • pilihan[0] SELALU jawaban yang benar. Urutan pilihan diacak saat tampil.
//   • Urutan soal di dalam satu level = urutan belajar (dari yang paling dasar).
//     Soal ditampilkan sesuai urutan ini, jadi taruh soal baru di tempat yang pas.
//   • `jelas` menjelaskan KENAPA. `modul` = nomor modul di modul.html (opsional).
//     `sumber` = asal angka/data (opsional; tampil kecil di bawah penjelasan).
//   • Hindari angka yang cepat basi. Kalau terpaksa memakai angka, sebut tanggal
//     dan sumbernya di `sumber`.
//   • Tanda kutip tunggal di dalam teks harus ditulis \' supaya string tidak putus.

window.KUIS_LEVEL = [
  { kode: 'blockchain', nomor: 1,  nama: 'Teknologi blockchain',        warna: '#4f7a68', ringkas: 'Blok, hash, node, konsensus, kunci publik & privat, layer 1 & 2 — fondasi sebelum membahas koin apa pun.' },
  { kode: 'bitcoin',    nomor: 2,  nama: 'Bitcoin: teknologi & kegunaan', warna: '#c9a961', ringkas: 'Proof of Work, halving, 21 juta, Lightning, dan kenapa institusi memakainya sebagai penyimpan nilai.' },
  { kode: 'ethereum',   nomor: 3,  nama: 'Ethereum & smart contract',   warna: '#6b7fb5', ringkas: 'EVM, gas, The Merge, standar token, rollup, blob, staking dan restaking.' },
  { kode: 'layer1',     nomor: 4,  nama: 'Koin layer 1 lain & kegunaannya', warna: '#9fb8c9', ringkas: 'Solana, BNB, XRP, Cardano, TON, Tron, Avalanche, Monero, Zcash, Hyperliquid, dan lainnya — apa teknologinya, untuk apa dipakai.' },
  { kode: 'infra',      nomor: 5,  nama: 'Koin infrastruktur & aplikasi', warna: '#7aa37a', ringkas: 'Oracle, DEX, lending, staking, penyimpanan, komputasi, AI, RWA, lintas chain — fungsi tiap token.' },
  { kode: 'keamanan',   nomor: 6,  nama: 'Dompet & keamanan',           warna: '#b86b5c', ringkas: 'Seed phrase, hot & cold wallet, approve, phishing, rug pull, dan cara memeriksa pemegang token.' },
  { kode: 'stablecoin', nomor: 7,  nama: 'Stablecoin & bursa',          warna: '#5a9a9a', ringkas: 'Sejarah dan bisnis stablecoin, CEX vs DEX, order book vs AMM, likuiditas, dan nasib listing baru.' },
  { kode: 'defi',       nomor: 8,  nama: 'DeFi: cara kerjanya',         warna: '#8a6fb0', ringkas: 'Lending, LP, impermanent loss, ve-token, MEV, flash loan, bridge, perpetual & funding, pasar prediksi.' },
  { kode: 'token',      nomor: 9,  nama: 'Membaca token',               warna: '#6b5b95', ringkas: 'Kebutuhan dulu baru token, jantung protokol, nilai intrinsik, FDV × float, unlock, alokasi. Modul 1–5.' },
  { kode: 'pasar',      nomor: 10, nama: 'Siklus, makro & data on-chain', warna: '#c98a4b', ringkas: 'Tiga tahap altcoin, rantai makro, aliran ETF, mindshare, tahap adopsi, treasury company. Modul 6–7.' },
  { kode: 'mental',     nomor: 11, nama: 'Mental, alokasi & trading naratif', warna: '#a0526b', ringkas: 'Bias yang merugikan, aturan 1%, barbell, tiga skenario alokasi, take profit, dan aturan invalidasi. Modul 8–9.' },
];

window.KUIS_SOAL = [
// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 1 — TEKNOLOGI BLOCKCHAIN
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'blockchain', tanya: 'Blockchain paling tepat digambarkan sebagai…',
  pilihan: ['Buku catatan transaksi yang disalin di banyak komputer dan sangat sulit diubah', 'Database milik satu perusahaan teknologi', 'Aplikasi untuk menambang koin', 'Nama lain dari dompet digital'],
  jelas: 'Karena salinannya dipegang ribuan komputer sekaligus, tidak ada satu pihak yang bisa diam-diam mengubah catatan. Itu yang membuatnya bisa dipercaya tanpa perantara seperti bank.' },
{ level: 'blockchain', tanya: 'Apa isi satu "blok" di dalam blockchain?',
  pilihan: ['Sekumpulan transaksi, ditambah sidik jari (hash) dari blok sebelumnya', 'Satu koin crypto', 'Satu dompet pengguna', 'Satu server milik bursa'],
  jelas: 'Setiap blok menyimpan hash blok sebelumnya, sehingga blok-blok tersambung seperti rantai. Dari situlah namanya: block + chain.' },
{ level: 'blockchain', tanya: 'Fungsi hash (misalnya SHA-256) mengubah data apa pun menjadi…',
  pilihan: ['Sidik jari berukuran tetap; beda satu huruf saja, hasilnya berubah total dan tidak bisa dibalik', 'Data terenkripsi yang bisa dibuka dengan kata sandi', 'Salinan data yang lebih kecil tetapi bisa dikembalikan utuh', 'Nomor urut transaksi'],
  jelas: 'Hash bekerja satu arah. Karena perubahan sekecil apa pun mengubah seluruh hasilnya, pemalsuan langsung ketahuan.' },
{ level: 'blockchain', tanya: 'Kenapa mengubah transaksi yang sudah lama tercatat hampir mustahil?',
  pilihan: ['Mengubah satu blok merusak hash semua blok sesudahnya, dan mayoritas jaringan akan menolaknya', 'Karena dilindungi kata sandi admin', 'Karena datanya disimpan di satu server yang dijaga ketat', 'Karena transaksi lama otomatis dihapus'],
  jelas: 'Penyerang harus menghitung ulang semua blok setelahnya lebih cepat dari seluruh jaringan jujur. Makin dalam sebuah blok tertimbun, makin mahal mengubahnya.' },
{ level: 'blockchain', tanya: 'Apa itu "node"?',
  pilihan: ['Komputer yang menyimpan salinan blockchain dan memeriksa bahwa semua transaksi mengikuti aturan', 'Akun admin sebuah bursa', 'Kode rahasia untuk membuka dompet', 'Satuan terkecil sebuah koin'],
  jelas: 'Makin banyak node yang tersebar dan dijalankan pihak berbeda, makin terdesentralisasi jaringannya — dan makin sulit disensor.' },
{ level: 'blockchain', tanya: 'Transaksi yang sudah dikirim tetapi belum masuk blok menunggu di…',
  pilihan: ['Mempool', 'Cold wallet', 'Smart contract', 'Order book'],
  jelas: 'Mempool adalah ruang tunggu. Di sinilah bot MEV mengintip transaksi orang lain sebelum dieksekusi — materi yang dibahas di level DeFi.' },
{ level: 'blockchain', tanya: '"Mekanisme konsensus" adalah…',
  pilihan: ['Aturan yang membuat ribuan node sepakat soal transaksi mana yang sah, tanpa pemimpin pusat', 'Voting pemegang saham perusahaan crypto', 'Persetujuan pemerintah atas sebuah koin', 'Kesepakatan harga antar-bursa'],
  jelas: 'Dua keluarga besar: Proof of Work (Bitcoin) dan Proof of Stake (Ethereum sejak 2022, Solana, Cardano, dan banyak lagi).' },
{ level: 'blockchain', tanya: 'Dalam Proof of Work, keamanan jaringan datang dari…',
  pilihan: ['Penambang yang berlomba memecahkan teka-teki komputasi, membakar listrik dan perangkat sungguhan', 'Jumlah pengikut media sosial', 'Deposit uang di bank', 'Tanda tangan pemerintah'],
  jelas: 'Menulis blok palsu berarti harus mengalahkan daya komputasi seluruh jaringan jujur — biayanya sangat mahal. Pemenang tiap blok menerima imbalan koin baru dan fee.' },
{ level: 'blockchain', tanya: 'Di Ethereum dan banyak jaringan Proof of Stake lain, validator yang curang dihukum dengan cara…',
  pilihan: ['Sebagian koin yang ia kunci (stake) dipotong — disebut slashing', 'Dilaporkan ke polisi', 'Diblokir dari media sosial', 'Dikenai pajak lebih tinggi'],
  jelas: 'Validator menaruh modalnya sendiri sebagai jaminan. Curang berarti kehilangan uang, jadi kejujuran lebih menguntungkan. Tidak semua PoS memakai slashing — Cardano, misalnya, tidak memotong stake.' },
{ level: 'blockchain', tanya: 'Kenapa PoW dan PoS tahan terhadap "sybil attack" (satu pihak membuat ribuan identitas palsu)?',
  pilihan: ['Karena bobot suara dihitung dari daya komputasi atau jumlah stake, bukan dari jumlah identitas', 'Karena setiap node wajib KYC', 'Karena jaringan membatasi jumlah dompet', 'Karena identitas palsu otomatis terhapus'],
  jelas: 'Membuat seribu akun gratis, tetapi membuat seribu kali daya komputasi atau stake itu mahal. Sybil attack tetap jadi ancaman bagi voting DAO dan airdrop yang menghitung per akun.',
  sumber: 'Materi Messari yang dibahas Akademi Crypto, Juli 2025' },
{ level: 'blockchain', tanya: 'Apa yang BISA dilakukan penyerang yang menguasai 51% daya jaringan?',
  pilihan: ['Membatalkan transaksinya sendiri yang baru terjadi (double spend) dan menyensor transaksi', 'Mengambil koin dari dompet siapa pun', 'Mengubah batas suplai koin', 'Membaca kunci privat semua pengguna'],
  jelas: 'Penyerang 51% tetap tidak bisa memalsukan tanda tangan orang lain. Bahayanya ada pada penulisan ulang transaksi terbaru — itulah kenapa bursa menunggu beberapa konfirmasi.' },
{ level: 'blockchain', tanya: 'Kunci privat dipakai untuk…',
  pilihan: ['Menandatangani transaksi secara digital — membuktikan pemiliknya setuju tanpa membuka kuncinya', 'Menerima koin dari orang lain', 'Mempercepat transaksi', 'Mengganti alamat dompet'],
  jelas: 'Kunci publik (dan alamat yang diturunkan darinya) boleh dibagikan. Kunci privat tidak pernah. Siapa pun yang memegangnya menguasai dompet itu.' },
{ level: 'blockchain', tanya: 'Merkle tree dalam sebuah blok berguna untuk…',
  pilihan: ['Meringkas semua transaksi menjadi satu hash, sehingga satu transaksi bisa dibuktikan ada tanpa mengunduh seluruh blok', 'Menyimpan gambar NFT', 'Mengacak urutan transaksi', 'Menghitung harga koin'],
  jelas: 'Berkat Merkle tree, dompet ringan di HP bisa memverifikasi transaksi tanpa menyimpan seluruh blockchain.' },
{ level: 'blockchain', tanya: '"Finality" berarti…',
  pilihan: ['Titik ketika sebuah transaksi tidak bisa dibatalkan lagi', 'Transaksi terakhir dalam sehari', 'Blok terakhir yang akan pernah dibuat', 'Harga penutupan pasar'],
  jelas: 'Setiap jaringan punya waktu finality berbeda — dari detik sampai sekitar satu jam untuk keyakinan tinggi di Bitcoin.' },
{ level: 'blockchain', tanya: 'Trilema blockchain menyatakan bahwa sulit memaksimalkan tiga hal ini sekaligus:',
  pilihan: ['Desentralisasi, keamanan, dan skalabilitas', 'Harga, volume, dan kapitalisasi', 'Privasi, kecepatan, dan warna antarmuka', 'Pendiri, investor, dan komunitas'],
  jelas: 'Chain yang sangat cepat biasanya mengorbankan jumlah node atau keamanan. Rollup dan sharding adalah upaya melonggarkan trilema ini.' },
{ level: 'blockchain', tanya: 'Apa beda layer 1 dan layer 2?',
  pilihan: ['Layer 2 memproses transaksi di luar layer 1 lalu menyelesaikan hasilnya di layer 1, sehingga ikut meminjam keamanannya', 'Layer 2 adalah versi berbayar dari layer 1', 'Layer 2 tidak memakai blockchain sama sekali', 'Layer 1 hanya untuk NFT'],
  jelas: 'Contoh: Lightning di atas Bitcoin; Arbitrum, Optimism, dan Base di atas Ethereum.' },
{ level: 'blockchain', tanya: 'Hard fork adalah…',
  pilihan: ['Perubahan aturan yang tidak kompatibel ke belakang; kalau sebagian komunitas menolak, lahir chain baru', 'Peretasan besar pada bursa', 'Pembagian koin gratis', 'Pemindahan koin ke cold wallet'],
  jelas: 'Contoh: Ethereum Classic lahir tahun 2016 dari penolakan hard fork setelah peretasan The DAO; Bitcoin Cash lahir tahun 2017 dari perdebatan ukuran blok.' },
{ level: 'blockchain', tanya: 'Sebuah chain mengklaim mampu 400.000 transaksi per detik. Bagaimana membacanya?',
  pilihan: ['Itu kapasitas teoretis; yang penting berapa transaksi nyata yang benar-benar dipakai orang', 'Pasti lebih baik dari semua chain lain', 'Berarti tokennya pasti naik', 'Berarti jaringannya paling aman'],
  jelas: 'Riset Delphi (Maret 2025) menunjukkan jurang besar antara TPS teoretis dan pemakaian nyata di hampir semua chain. Kapasitas tanpa permintaan hanyalah janji.',
  sumber: 'Delphi Digital via Akademi Crypto, Maret 2025' },
{ level: 'blockchain', tanya: 'Kenapa komputer kuantum dianggap ancaman jangka panjang bagi crypto?',
  pilihan: ['Algoritma Shor berpotensi menghitung kunci privat dari kunci publik yang terlihat saat bertransaksi', 'Komputer kuantum bisa menambang semua koin dalam sehari', 'Komputer kuantum mematikan internet', 'Karena listriknya sangat mahal'],
  jelas: 'Hampir semua chain memakai tanda tangan berbasis kurva eliptik — ECDSA/secp256k1 di Bitcoin dan Ethereum, Ed25519 di Solana, Cardano, dan lainnya. Semuanya rentan terhadap algoritma Shor. Solusinya adalah migrasi ke kriptografi pasca-kuantum sebelum komputer kuantum cukup kuat.',
  sumber: 'Delphi Digital via Akademi Crypto, Desember 2025' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 2 — BITCOIN
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'bitcoin', tanya: 'Bitcoin pertama kali diperkenalkan lewat…',
  pilihan: ['Whitepaper tahun 2008 oleh Satoshi Nakamoto, sosok bernama samaran', 'Pengumuman bank sentral AS', 'Proyek riset Google', 'Perusahaan rintisan di Silicon Valley'],
  jelas: 'Judulnya "Bitcoin: A Peer-to-Peer Electronic Cash System". Jaringannya berjalan sejak Januari 2009, dan identitas asli Satoshi tidak pernah diketahui.' },
{ level: 'bitcoin', tanya: 'Berapa jumlah maksimum Bitcoin yang akan pernah ada?',
  pilihan: ['21 juta', '100 juta', 'Tidak terbatas', '1 miliar'],
  jelas: 'Batas ini tertulis di aturan jaringan. Koin baru dicetak lewat imbalan blok yang terus mengecil sampai berhenti sekitar tahun 2140.' },
{ level: 'bitcoin', tanya: 'Satoshi adalah…',
  pilihan: ['Satuan terkecil Bitcoin: 0,00000001 BTC', 'Nama bursa pertama', 'Koin pesaing Bitcoin', 'Nama jaringan uji Bitcoin'],
  jelas: 'Artinya Anda tidak perlu membeli 1 BTC utuh — pecahan kecil pun bisa.' },
{ level: 'bitcoin', tanya: 'Mekanisme konsensus Bitcoin adalah…',
  pilihan: ['Proof of Work dengan fungsi hash SHA-256', 'Proof of Stake', 'Proof of History', 'Voting pemegang token'],
  jelas: 'Penambang memakai mesin khusus (ASIC) untuk menebak hash yang memenuhi syarat kesulitan. Bitcoin tidak pernah pindah ke Proof of Stake.' },
{ level: 'bitcoin', tanya: 'Rata-rata satu blok Bitcoin tercipta setiap…',
  pilihan: ['Sekitar 10 menit', 'Sekitar 12 detik', 'Sekitar 1 detik', 'Sekitar 1 jam'],
  jelas: '12 detik adalah waktu blok Ethereum. Bitcoin sengaja lambat supaya jaringan yang tersebar di seluruh dunia sempat sinkron.' },
{ level: 'bitcoin', tanya: 'Kalau makin banyak penambang bergabung, kenapa blok Bitcoin tidak jadi lebih cepat?',
  pilihan: ['Tingkat kesulitan disesuaikan otomatis setiap 2.016 blok (±2 minggu) supaya waktu blok tetap ±10 menit', 'Karena jumlah penambang dibatasi', 'Karena pemerintah mengatur kecepatannya', 'Karena Bitcoin berhenti saat terlalu ramai'],
  jelas: 'Penyesuaian kesulitan (difficulty adjustment) inilah yang membuat jadwal pencetakan Bitcoin bisa diprediksi puluhan tahun ke depan.' },
{ level: 'bitcoin', tanya: 'Apa yang terjadi saat halving Bitcoin?',
  pilihan: ['Imbalan penambang per blok dipotong setengah', 'Harga Bitcoin otomatis dibagi dua', 'Jumlah Bitcoin yang sudah beredar dipotong setengah', 'Biaya transaksi turun setengah'],
  jelas: 'Setiap 210.000 blok (±4 tahun). Halving April 2024 menurunkan imbalan dari 6,25 menjadi 3,125 BTC per blok. Yang berkurang adalah laju pencetakan, bukan koin yang sudah ada.' },
{ level: 'bitcoin', tanya: 'Lightning Network adalah…',
  pilihan: ['Jaringan layer 2 untuk pembayaran Bitcoin cepat dan murah lewat kanal pembayaran di luar chain utama', 'Koin baru pesaing Bitcoin', 'Alat penambangan yang lebih cepat', 'Bursa khusus Bitcoin'],
  jelas: 'Hanya pembukaan dan penutupan kanal yang dicatat di chain utama. Di dalam kanal, pembayaran kecil bisa terjadi dalam hitungan detik.' },
{ level: 'bitcoin', tanya: 'Apakah transaksi Bitcoin anonim?',
  pilihan: ['Tidak — pseudonim: semua transaksi terbuka untuk publik, hanya alamatnya tidak memuat nama', 'Ya, sepenuhnya anonim dan tidak bisa dilacak', 'Hanya admin Bitcoin yang bisa melihat', 'Transaksi dihapus setelah sebulan'],
  jelas: 'Pengirim, penerima, dan jumlah tercatat terbuka selamanya. Begitu sebuah alamat dikaitkan dengan identitas (misalnya lewat bursa KYC), riwayatnya bisa dilacak.' },
{ level: 'bitcoin', tanya: 'Kenapa kemampuan pemrograman (programmability) Bitcoin sengaja dibuat rendah?',
  pilihan: ['Bahasa skripnya dibatasi demi keamanan; Bitcoin fokus menjadi uang yang sulit diubah, bukan platform aplikasi', 'Karena penciptanya tidak bisa memprogram', 'Karena dilarang regulator', 'Karena Bitcoin sudah usang'],
  jelas: 'Dalam kerangka "cloud thesis": Bitcoin = uang yang bisa diverifikasi, Ethereum = komputasi yang bisa diverifikasi. Keduanya menjawab kebutuhan berbeda.',
  sumber: 'EigenCloud & Delphi Digital via Akademi Crypto, Oktober 2025' },
{ level: 'bitcoin', tanya: 'Kegunaan utama Bitcoin yang membuat institusi dan perusahaan membelinya adalah…',
  pilihan: ['Penyimpan nilai dengan suplai terbatas — sering disebut "emas digital"', 'Menjalankan aplikasi DeFi', 'Membayar gas di Ethereum', 'Membeli NFT game'],
  jelas: 'Akademi Crypto menduga Pantera Capital menaruh sekitar 70% dananya di Bitcoin walau dikenal sebagai investor altcoin — Bitcoin diperlakukan sebagai jangkar portofolio.',
  sumber: 'Akademi Crypto, kanal smart-money, Mei 2024' },
{ level: 'bitcoin', tanya: 'ETF Bitcoin spot pertama kali disetujui di Amerika Serikat pada…',
  pilihan: ['Januari 2024', 'Januari 2009', 'Desember 2017', 'Juli 2021'],
  jelas: 'Sejak itu aliran dana ETF masuk-keluar menjadi salah satu penggerak harga harian yang bisa diperiksa datanya.' },
{ level: 'bitcoin', tanya: '"Dominasi Bitcoin" adalah…',
  pilihan: ['Porsi kapitalisasi Bitcoin dari seluruh kapitalisasi pasar crypto', 'Jumlah penambang Bitcoin', 'Persentase transaksi dunia yang memakai Bitcoin', 'Harga Bitcoin dibagi harga emas'],
  jelas: 'Dominasi naik biasanya berarti uang berlindung ke Bitcoin; turun sering menandakan uang mengalir ke altcoin.' },
{ level: 'bitcoin', tanya: 'Menurut data yang dibahas Akademi Crypto (Des 2024), apa efek menambah 2,5–5% Bitcoin ke portofolio saham-obligasi?',
  pilihan: ['Imbal hasil naik dan rasio Sharpe/Sortino membaik, walau volatilitas ikut naik', 'Portofolio pasti rugi', 'Tidak ada pengaruh sama sekali', 'Volatilitas turun ke nol'],
  jelas: 'Porsi kecil Bitcoin memperbaiki imbal hasil per unit risiko — pada data November 2021 sampai Oktober 2024, bahkan bila Bitcoin dibeli di puncak siklus sebelumnya.',
  sumber: 'Swan Research & Delphi Digital via Akademi Crypto, Desember 2024' },
{ level: 'bitcoin', tanya: 'Apa itu "law of diminishing drawdown" pada Bitcoin?',
  pilihan: ['Penurunan dari puncak ke dasar di setiap siklus cenderung makin kecil seiring kapitalisasinya membesar', 'Harga Bitcoin tidak pernah turun lagi', 'Setiap siklus penurunannya makin dalam', 'Bitcoin hanya turun saat halving'],
  jelas: 'Dulu drawdown bisa ±80%. Makin besar asetnya, makin sulit digerakkan — ke bawah maupun ke atas. Potensi kenaikannya pun ikut mengecil.',
  sumber: 'Into the Cryptoverse via Akademi Crypto, Januari 2025' },
{ level: 'bitcoin', tanya: 'Babylon memungkinkan pemegang Bitcoin untuk…',
  pilihan: ['Men-stake BTC asli (tanpa bridge) untuk ikut mengamankan chain lain dan mendapat imbalan', 'Menambang Bitcoin lewat HP', 'Mengubah Bitcoin menjadi Proof of Stake', 'Menggandakan jumlah Bitcoin'],
  jelas: 'BTC tetap di jaringan Bitcoin, tetapi bisa dipotong (slashing) kalau validator yang dijaminnya curang.' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 3 — ETHEREUM & SMART CONTRACT
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'ethereum', tanya: 'Ethereum diluncurkan tahun 2015 dengan gagasan utama…',
  pilihan: ['Blockchain yang bisa menjalankan program (smart contract), bukan hanya mencatat transfer uang', 'Bitcoin yang lebih cepat', 'Mata uang resmi sebuah negara', 'Jaringan khusus NFT'],
  jelas: 'Digagas Vitalik Buterin. Karena bisa diprogram, di atasnya lahir DeFi, stablecoin, NFT, dan ribuan token lain.' },
{ level: 'ethereum', tanya: 'Smart contract adalah…',
  pilihan: ['Program di blockchain yang menjalankan aturan secara otomatis', 'Kontrak kerja tim pengembang', 'Perjanjian jual beli di notaris', 'Aplikasi dompet di HP'],
  jelas: 'Smart contract berjalan persis seperti kodenya — tanpa perantara, tapi juga tanpa ampun. Kalau kodenya bercelah, celah itu ikut berjalan.' },
{ level: 'ethereum', tanya: 'EVM (Ethereum Virtual Machine) adalah…',
  pilihan: ['Mesin virtual yang menjalankan smart contract di semua node; chain lain yang "EVM-compatible" bisa menjalankan kontrak yang sama', 'Merek komputer tambang', 'Dompet resmi Ethereum', 'Bursa milik Ethereum Foundation'],
  jelas: 'Karena banyak chain (BNB Chain, Avalanche C-Chain, Arbitrum, Base) memakai EVM, aplikasi dan dompet yang sama bisa dipakai di semuanya.' },
{ level: 'ethereum', tanya: 'Gas di Ethereum adalah…',
  pilihan: ['Satuan kerja komputasi yang biayanya dibayar dalam ETH (sering dihitung dalam gwei)', 'Pajak pemerintah atas transaksi', 'Biaya langganan dompet', 'Komisi bursa'],
  jelas: 'Makin rumit transaksinya dan makin padat jaringannya, makin mahal gas-nya. 1 gwei = 0,000000001 ETH.' },
{ level: 'ethereum', tanya: 'Sejak pembaruan EIP-1559 (2021), apa yang terjadi pada "base fee" setiap transaksi?',
  pilihan: ['Dibakar (dihapus dari suplai)', 'Diberikan ke Vitalik Buterin', 'Disimpan di bank', 'Dikembalikan ke pengirim'],
  jelas: 'Saat jaringan ramai, ETH yang dibakar bisa lebih besar dari ETH baru yang dicetak — suplai bersih pun menyusut.' },
{ level: 'ethereum', tanya: '"The Merge" (September 2022) mengubah Ethereum dari…',
  pilihan: ['Proof of Work menjadi Proof of Stake — konsumsi energinya turun sekitar 99,9%', 'Layer 1 menjadi layer 2', 'Koin menjadi saham', 'Blockchain publik menjadi privat'],
  jelas: 'Sejak itu blok Ethereum dibuat validator yang men-stake ETH, bukan penambang.' },
{ level: 'ethereum', tanya: 'Berapa ETH yang dibutuhkan untuk menjalankan satu validator Ethereum sendiri?',
  pilihan: ['32 ETH', '1 ETH', '100 ETH', '0,1 ETH'],
  jelas: 'Yang punya kurang dari 32 ETH biasanya memakai liquid staking (misalnya Lido) atau layanan staking di bursa.' },
{ level: 'ethereum', tanya: 'Waktu satu blok (slot) Ethereum sekitar…',
  pilihan: ['12 detik', '10 menit', '1 menit', '1 detik'],
  jelas: 'Harga di AMM on-chain hanya diperbarui tiap blok, sehingga trader yang lebih cepat bisa memanfaatkan harga "basi" — materi toxic flow di level DeFi.' },
{ level: 'ethereum', tanya: 'ERC-20 dan ERC-721 adalah…',
  pilihan: ['Standar token: ERC-20 untuk token yang bisa dipertukarkan, ERC-721 untuk NFT yang unik', 'Nama dua bursa besar', 'Versi Ethereum lama dan baru', 'Kode negara penerbit token'],
  jelas: 'Standar membuat semua dompet dan bursa bisa langsung mengenali token baru tanpa integrasi khusus.' },
{ level: 'ethereum', tanya: 'Di mana gambar sebuah NFT ERC-721 biasanya disimpan?',
  pilihan: ['Di luar chain (IPFS, Arweave, atau server); token hanya menyimpan ID, pemilik, dan tautan ke metadata', 'Di dalam blok Ethereum secara utuh', 'Di dompet pembeli', 'Di bursa tempat membelinya'],
  jelas: 'Kalau tautan itu mengarah ke server biasa yang kemudian mati, gambarnya bisa hilang walau tokennya tetap ada.',
  sumber: 'Messari via Akademi Crypto, Desember 2025' },
{ level: 'ethereum', tanya: 'Apa beda optimistic rollup dan ZK rollup?',
  pilihan: ['Optimistic menganggap transaksi sah kecuali dibantah dalam masa sanggah; ZK membuktikan kebenarannya dengan bukti kriptografis', 'Optimistic lebih mahal, ZK gratis', 'Optimistic untuk Bitcoin, ZK untuk Solana', 'Tidak ada bedanya'],
  jelas: 'Karena ada masa sanggah, penarikan dari optimistic rollup seperti Arbitrum dan OP Mainnet ke Ethereum bisa memakan sekitar seminggu. ZK rollup (zkSync, Starknet) tidak perlu menunggu masa sanggah.' },
{ level: 'ethereum', tanya: 'Pembaruan EIP-4844 (2024) memperkenalkan "blob". Apa gunanya?',
  pilihan: ['Ruang data murah khusus untuk layer 2, sehingga biaya transaksi di L2 turun drastis', 'Jenis NFT baru', 'Koin baru pengganti ETH', 'Fitur privasi'],
  jelas: 'Peta jalannya berlanjut: Pectra, lalu PeerDAS (Fusaka), hingga full danksharding — semua untuk menambah kapasitas data bagi L2.',
  sumber: 'Delphi Digital via Akademi Crypto, Maret 2025' },
{ level: 'ethereum', tanya: 'Liquid staking (misalnya Lido dengan stETH) memungkinkan…',
  pilihan: ['Men-stake ETH sambil tetap memegang token cair yang bisa dipakai di DeFi', 'Menambang ETH dengan HP', 'Menarik ETH tanpa antre kapan pun tanpa risiko', 'Mencetak ETH baru'],
  jelas: 'Risikonya: token cair bisa diperdagangkan di bawah nilai ETH saat pasar panik (Juni 2022 stETH sempat diskon beberapa persen), dan ada risiko smart contract.' },
{ level: 'ethereum', tanya: 'Restaking (EigenLayer) adalah…',
  pilihan: ['Memakai ETH yang sudah di-stake untuk ikut mengamankan layanan lain, dengan hadiah tambahan dan risiko slashing tambahan', 'Staking dua kali agar hadiah dua kali lipat tanpa risiko', 'Menjual ETH lalu membelinya lagi', 'Staking di bursa terpusat'],
  jelas: 'Layanan yang menumpang keamanan ini disebut AVS (Actively Validated Services): oracle, bridge, data availability, dan lainnya.' },
{ level: 'ethereum', tanya: 'Porsi ETH yang di-stake naik dari ±11,5% (2022) menjadi ±34% (2026). Apa yang terjadi pada imbal hasil staking?',
  pilihan: ['Turun, dari ±5,8% ke ±2,6% — hadiah dibagi ke lebih banyak staker', 'Naik tiga kali lipat', 'Tetap sama', 'Menjadi nol'],
  jelas: 'Makin banyak yang ikut staking, makin kecil bagian masing-masing. Ini sebabnya muncul usulan menurunkan penerbitan ETH saat rasio staking tinggi.',
  sumber: 'Messari via Akademi Crypto, Agustus 2026' },
{ level: 'ethereum', tanya: 'Base, salah satu L2 terbesar, dibangun oleh…',
  pilihan: ['Coinbase — awalnya di atas OP Stack milik Optimism', 'Binance', 'Tim Solana', 'Pemerintah AS'],
  jelas: 'Pada 2026 Base keluar dari Superchain Optimism dan beralih ke sistem bukti ganda (TEE dan ZK). Base tidak punya token sendiri saat diluncurkan. Pendapatannya dari fee sequencer sebagian besar mengalir ke Coinbase — contoh bagaimana aktivitas jaringan tidak otomatis menjadi nilai token.' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 4 — KOIN LAYER 1 LAIN: TEKNOLOGI & KEGUNAAN
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'layer1', tanya: 'Solana dikenal cepat dan murah karena…',
  pilihan: ['Proof of Stake yang dibantu Proof of History (jam kriptografis) dan eksekusi transaksi paralel', 'Memakai Proof of Work seperti Bitcoin', 'Tidak memakai blockchain', 'Hanya punya satu validator'],
  jelas: 'Kegunaan utamanya hari ini: DEX, memecoin, pembayaran stablecoin, dan aplikasi konsumen. Kompensasinya, menjalankan validator butuh perangkat keras mahal. Konsensus baru Solana, Alpenglow, dijadwalkan menggantikan Tower BFT dan Proof of History mulai Oktober 2026.' },
{ level: 'layer1', tanya: 'Dalam rantai memecoin Solana awal 2025, Pump.fun, Raydium, dan Jupiter berperan sebagai…',
  pilihan: ['Pump.fun = tempat meluncurkan koin; Raydium = DEX penyedia likuiditas; Jupiter = agregator yang mencari rute termurah', 'Ketiganya dompet', 'Ketiganya bursa terpusat', 'Ketiganya validator'],
  jelas: 'Aplikasi Solana saling bergantung. Satu mata rantai terganggu, seluruh alur perdagangan ikut terganggu. Sejak Maret 2025, koin yang lulus dari Pump.fun pindah ke DEX milik Pump.fun sendiri (PumpSwap).',
  sumber: 'Messari via Akademi Crypto, Februari 2025' },
{ level: 'layer1', tanya: 'Kegunaan utama BNB adalah…',
  pilihan: ['Membayar gas di BNB Smart Chain dan mendapat potongan fee di bursa Binance', 'Mata uang resmi Tiongkok', 'Stablecoin berpatokan dolar', 'Token privasi'],
  jelas: 'BNB adalah token ekosistem bursa. Nilainya sangat terkait nasib Binance — itu kekuatan sekaligus risiko konsentrasinya.' },
{ level: 'layer1', tanya: 'XRP Ledger dirancang terutama untuk…',
  pilihan: ['Pembayaran dan transfer nilai lintas negara yang cepat dan murah', 'Menjalankan game on-chain', 'Penambangan Proof of Work', 'Penyimpanan file'],
  jelas: 'XRPL memakai protokol konsensus sendiri — bukan Proof of Work, bukan Proof of Stake — sehingga tidak ada staking bawaan. Imbal hasil XRP biasanya datang dari platform pihak ketiga atau DeFi.',
  sumber: 'Messari via Akademi Crypto, Juni 2026' },
{ level: 'layer1', tanya: 'Cardano (ADA) memakai konsensus Proof of Stake bernama…',
  pilihan: ['Ouroboros', 'Proof of History', 'Tendermint', 'SHA-256'],
  jelas: 'Cardano dikenal dengan pendekatan berbasis riset akademis yang ditinjau sejawat, dan bahasa smart contract Plutus berbasis Haskell.' },
{ level: 'layer1', tanya: 'TON (The Open Network) punya keunggulan distribusi karena…',
  pilihan: ['Terhubung dengan Telegram yang punya ratusan juta pengguna, dan memakai dynamic sharding untuk skala besar', 'Didukung bank sentral Eropa', 'Satu-satunya chain Proof of Work modern', 'Tidak memakai smart contract'],
  jelas: 'Shard di TON membelah saat ramai dan bergabung saat sepi: masterchain → workchain → shardchain → account chain.',
  sumber: 'Messari via Akademi Crypto, April 2026' },
{ level: 'layer1', tanya: 'Jaringan Tron (TRX) paling banyak dipakai untuk…',
  pilihan: ['Transfer stablecoin USDT dengan biaya murah', 'Penambangan Bitcoin', 'Penyimpanan file permanen', 'Pasar prediksi'],
  jelas: 'Porsi besar USDT beredar di Tron karena biayanya murah dan sudah didukung banyak bursa, terutama untuk pengiriman di negara berkembang.' },
{ level: 'layer1', tanya: 'Konsep utama Avalanche (Avalanche9000) adalah…',
  pilihan: ['Banyak L1 mandiri yang bisa dibuat khusus per aplikasi, tetap saling terhubung', 'Satu chain tunggal untuk semua aplikasi', 'Blockchain tanpa validator', 'Chain khusus Bitcoin'],
  jelas: 'Perusahaan atau game bisa punya chain sendiri dengan aturan sendiri — dulu disebut subnet.' },
{ level: 'layer1', tanya: 'Polkadot menghubungkan banyak chain (parachain) yang…',
  pilihan: ['Berbagi keamanan dari satu relay chain pusat', 'Masing-masing punya penambang sendiri', 'Tidak bisa saling berkomunikasi', 'Semuanya milik satu perusahaan'],
  jelas: 'Model "shared security": chain kecil tidak perlu membangun keamanan dari nol.' },
{ level: 'layer1', tanya: 'Sui dan Aptos sama-sama memakai bahasa smart contract…',
  pilihan: ['Move, dengan eksekusi transaksi paralel', 'Solidity', 'Bitcoin Script', 'Tidak memakai smart contract'],
  jelas: 'Move lahir dari proyek Diem (dulu Libra) milik Meta. Sui memakai model objek; Aptos menambah pipelining untuk mempercepat produksi blok.' },
{ level: 'layer1', tanya: 'Litecoin (2011) sering disebut "perak" untuk "emas" Bitcoin karena…',
  pilihan: ['Merupakan turunan Bitcoin dengan blok ±2,5 menit, algoritma Scrypt, dan suplai maksimum 84 juta', 'Dijamin cadangan perak', 'Dibuat Satoshi Nakamoto', 'Memakai Proof of Stake'],
  jelas: 'Litecoin dibuat Charlie Lee sebagai versi lebih cepat dan ringan dari Bitcoin.' },
{ level: 'layer1', tanya: 'Dogecoin berbeda dari Bitcoin dalam hal suplai karena…',
  pilihan: ['Tidak punya batas suplai maksimum — koin baru terus dicetak setiap tahun', 'Suplainya hanya 21 ribu', 'Suplainya dikurangi setiap hari', 'Dijamin dolar AS'],
  jelas: 'Dibuat tahun 2013 sebagai lelucon bergambar anjing Shiba Inu. Nilainya digerakkan komunitas dan budaya internet, bukan arus kas.' },
{ level: 'layer1', tanya: 'Monero menyembunyikan identitas pengirim dengan teknologi…',
  pilihan: ['Ring signature — tanda tangan pengirim dicampur dengan kunci-kunci umpan, sehingga pengirim asli tidak bisa dipastikan', 'Mengirim transaksi lewat email', 'Menghapus blockchain setiap minggu', 'Proof of History'],
  jelas: 'Monero juga memakai alamat siluman (stealth address) dan menyembunyikan jumlah transaksi. Karena itu banyak bursa men-delist koin privasi di bawah tekanan regulator.',
  sumber: 'Delphi Digital via Akademi Crypto, Maret 2026' },
{ level: 'layer1', tanya: 'Zcash memungkinkan transaksi terlindung (shielded) dengan teknologi…',
  pilihan: ['zk-SNARK — bukti bahwa transaksi sah tanpa membuka pengirim, penerima, atau jumlahnya', 'Ring signature', 'Proof of Liquidity', 'Mixer terpusat'],
  jelas: 'Di Zcash privasinya opsional: ada alamat transparan seperti Bitcoin dan alamat shielded.' },
{ level: 'layer1', tanya: 'Hyperliquid adalah layer 1 yang dirancang khusus untuk…',
  pilihan: ['Bursa derivatif on-chain dengan order book penuh (perpetual, spot, dan pasar lain)', 'Penyimpanan file', 'Game NFT', 'Penambangan Bitcoin'],
  jelas: 'Sebagian besar fee protokolnya dipakai membeli kembali token HYPE — contoh token yang terhubung langsung ke pendapatan.',
  sumber: 'Delphi Digital & Messari via Akademi Crypto, 2025–2026' },
{ level: 'layer1', tanya: 'Saat diluncurkan (2025), Berachain memakai konsensus "Proof of Liquidity". Apa ciri khasnya?',
  pilihan: ['Validator men-stake BERA dan mengarahkan emisi BGT ke pool likuiditas (Reward Vault); pemegang BGT mendelegasikan BGT-nya ke validator pilihan', 'Tidak memakai validator sama sekali', 'Hanya satu token untuk semua fungsi', 'Memakai Proof of Work'],
  jelas: 'Tujuannya mengikat keamanan jaringan dengan likuiditas DeFi di atasnya. Menurut dokumentasi resminya, BGT dihentikan pada 8 Juli 2026 dan hadiah blok kini memakai WBERA — contoh bahwa desain tokenomics bisa berubah di tengah jalan.',
  sumber: 'Messari via Akademi Crypto, April 2025' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 5 — KOIN INFRASTRUKTUR & APLIKASI: TEKNOLOGI & KEGUNAAN
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'infra', tanya: 'Kenapa blockchain butuh "oracle"?',
  pilihan: ['Blockchain tidak bisa melihat data dunia luar (harga, cuaca, skor) sendiri; oracle yang membawanya masuk', 'Untuk menambang koin', 'Untuk menyimpan kunci privat', 'Untuk mempercepat blok'],
  jelas: 'Protokol lending butuh harga yang akurat untuk tahu kapan harus melikuidasi. Oracle yang salah = likuidasi yang salah.' },
{ level: 'infra', tanya: 'Kegunaan utama Chainlink (LINK) adalah…',
  pilihan: ['Jaringan oracle: data harga untuk DeFi, angka acak yang bisa diverifikasi (VRF), dan pesan lintas chain (CCIP)', 'Stablecoin', 'Memecoin', 'Dompet hardware'],
  jelas: 'VRF dipakai game, NFT, dan undian: angka acak dibuat bersama bukti kriptografis yang diverifikasi di chain, sehingga tidak bisa dimanipulasi.',
  sumber: 'Messari via Akademi Crypto, 2025' },
{ level: 'infra', tanya: 'Uniswap menentukan harga tanpa order book, dengan rumus…',
  pilihan: ['x × y = k — hasil kali jumlah dua token di pool harus tetap', 'Harga = suara pemegang UNI', 'Harga ditetapkan admin setiap jam', 'Harga = harga di Binance'],
  jelas: 'Membeli token A membuat jumlah A di pool berkurang sehingga harganya naik. Order yang besar terhadap pool kecil = slippage besar.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2025' },
{ level: 'infra', tanya: 'Aave adalah protokol untuk…',
  pilihan: ['Pinjam-meminjam: penyetor mendapat bunga, peminjam wajib menaruh jaminan lebih besar dari pinjamannya', 'Menambang Bitcoin', 'Membuat NFT', 'Transfer lintas negara lewat bank'],
  jelas: 'Penyetor menerima aToken yang nilainya bertambah seiring bunga; peminjam mendapat token utang. Kalau nilai jaminan turun terlalu jauh, posisi dilikuidasi otomatis.',
  sumber: 'Delphi Digital via Akademi Crypto, April 2025' },
{ level: 'infra', tanya: 'Lido (LDO) terkenal sebagai…',
  pilihan: ['Penyedia liquid staking ETH terbesar — penyetor menerima stETH', 'Bursa terpusat', 'Stablecoin algoritmik', 'Chain privasi'],
  jelas: 'Karena menguasai porsi besar ETH yang di-stake, Lido juga sering dibahas sebagai risiko sentralisasi Ethereum.' },
{ level: 'infra', tanya: 'Filecoin (FIL) dan Arweave (AR) sama-sama jaringan penyimpanan. Apa bedanya?',
  pilihan: ['Filecoin = pasar sewa penyimpanan dengan bukti berkala; Arweave = penyimpanan permanen dengan bayar sekali', 'Filecoin untuk video, Arweave untuk musik', 'Keduanya bursa', 'Tidak ada bedanya'],
  jelas: 'Di Filecoin, penambang harus terus membuktikan bahwa file masih disimpan. Keduanya alternatif dari Google Drive atau AWS yang tidak bergantung pada satu perusahaan.' },
{ level: 'infra', tanya: 'Akash Network (AKT) menyediakan…',
  pilihan: ['Pasar komputasi awan terdesentralisasi — penyedia server menawar untuk menjalankan aplikasi pengguna', 'Stablecoin', 'Dompet', 'Oracle harga'],
  jelas: 'Alternatif AWS, Google Cloud, dan Azure. Termasuk sektor DePIN (infrastruktur fisik terdesentralisasi).',
  sumber: 'Messari via Akademi Crypto, Mei 2025' },
{ level: 'infra', tanya: 'Bittensor (TAO) memberi insentif token kepada…',
  pilihan: ['Penambang dan validator di "subnet" yang menyumbang model AI, data, atau komputasi yang berguna', 'Pemegang saham Nvidia', 'Pengguna media sosial', 'Siapa pun yang membuka aplikasi'],
  jelas: 'Setiap subnet adalah pasar untuk satu jenis pekerjaan AI; kualitas kerjanya dinilai dan diberi emisi token.' },
{ level: 'infra', tanya: 'The Graph (GRT) sering dijuluki "Google-nya blockchain" karena…',
  pilihan: ['Mengindeks data blockchain sehingga aplikasi bisa mencarinya dengan cepat', 'Dibuat oleh Google', 'Menyediakan mesin pencari web', 'Menjual iklan'],
  jelas: 'Membaca data mentah langsung dari node itu lambat. Pengindeks menyusunnya agar aplikasi bisa bertanya dengan cepat.' },
{ level: 'infra', tanya: 'Kegunaan Polygon (POL) hari ini paling tepat digambarkan sebagai…',
  pilihan: ['Solusi skala untuk Ethereum yang kini menyatukan banyak chain lewat AggLayer', 'Bursa terpusat', 'Stablecoin', 'Koin privasi'],
  jelas: 'AggLayer menyatukan likuiditas dan pengguna banyak chain lewat satu bridge bersama, diamankan bukti kriptografis.',
  sumber: 'Messari via Akademi Crypto, Mei 2025' },
{ level: 'infra', tanya: 'Ondo Finance dikenal di sektor RWA karena…',
  pilihan: ['Menokenisasi aset dunia nyata seperti obligasi pemerintah AS agar bisa dipegang dan dipakai di chain', 'Membuat memecoin', 'Menambang Bitcoin', 'Menjual kartu grafis'],
  jelas: 'RWA (real-world assets) adalah salah satu sektor dengan pertumbuhan paling nyata: dari obligasi, kredit swasta, sampai saham tertokenisasi.' },
{ level: 'infra', tanya: 'Ethena (USDe) disebut "dolar sintetis" karena…',
  pilihan: ['Nilainya dijaga lewat jaminan crypto yang di-hedge dengan posisi short perpetual (delta-netral), bukan dolar di bank', 'Dicetak bank sentral', 'Dijamin emas', 'Tidak punya jaminan apa pun'],
  jelas: 'Imbal hasilnya terutama dari funding rate posisi short, ditambah hasil jaminan lain (misalnya obligasi tertokenisasi). Saat funding negatif lama, model ini tertekan — risiko yang berbeda dari stablecoin berjamin kas.' },
{ level: 'infra', tanya: 'Worldcoin (WLD) memakai pemindai iris mata untuk…',
  pilihan: ['Membuktikan seseorang adalah manusia unik (proof-of-personhood) tanpa membuka identitasnya', 'Membuka pintu rumah', 'Menambang Bitcoin', 'Mengukur kesehatan'],
  jelas: 'Kegunaannya: melawan bot, membagi airdrop secara adil, dan satu orang satu suara. Kritiknya: soal data biometrik yang diserahkan.',
  sumber: 'Delphi Digital & Messari via Akademi Crypto, Mei–Juli 2025' },
{ level: 'infra', tanya: 'LayerZero (ZRO) adalah…',
  pilihan: ['Protokol pesan lintas chain: pesan diverifikasi jaringan verifier (DVN) lalu dieksekusi di chain tujuan', 'Layer 1 tercepat', 'Dompet hardware', 'Stablecoin'],
  jelas: 'Keamanannya bergantung pada kombinasi verifier yang dipilih aplikasi, bukan satu penjaga tunggal seperti bridge lama.',
  sumber: 'Messari via Akademi Crypto, April 2026' },
{ level: 'infra', tanya: 'Pendle memisahkan aset berimbal hasil menjadi dua token. Apa itu?',
  pilihan: ['PT (principal token, pokoknya) dan YT (yield token, imbal hasilnya)', 'BTC dan ETH', 'Token beli dan token jual', 'Token pria dan wanita'],
  jelas: 'Dengan memecahnya, orang bisa mengunci imbal hasil tetap (beli PT) atau berspekulasi pada imbal hasil (beli YT).' },
{ level: 'infra', tanya: 'Polymarket adalah…',
  pilihan: ['Pasar prediksi on-chain: orang bertaruh pada hasil peristiwa dengan token YES dan NO', 'Bursa saham Polandia', 'Chain milik Polygon', 'Stablecoin'],
  jelas: 'Pesaing utamanya di AS adalah Kalshi yang teregulasi CFTC. Sejak akhir 2025 Polymarket juga menempuh jalur izin CFTC lewat akuisisi bursa berlisensi untuk melayani pengguna AS. Keunggulannya: jangkauan global dan ekosistem alat on-chain.',
  sumber: 'Delphi Digital via Akademi Crypto, Agustus & Oktober 2025' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 6 — DOMPET & KEAMANAN
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'keamanan', tanya: 'Alamat dompet dan kunci privat — mana yang boleh dibagikan ke orang lain?',
  pilihan: ['Alamat dompet saja', 'Keduanya', 'Kunci privat saja', 'Tidak ada yang boleh'],
  jelas: 'Alamat seperti nomor rekening: dibagikan supaya orang bisa mengirim. Kunci privat seperti tanda tangan sekaligus PIN.' },
{ level: 'keamanan', tanya: 'Seed phrase (12 atau 24 kata) adalah…',
  pilihan: ['Kunci induk yang bisa memulihkan seluruh dompet — dan semua alamat di berbagai chain yang diturunkan darinya', 'Kata sandi akun bursa', 'Nama pengguna dompet', 'Kode promo'],
  jelas: 'Standarnya disebut BIP39. Dari satu seed, dompet menurunkan banyak alamat (BIP44) — kehilangan seed berarti kehilangan semuanya sekaligus.' },
{ level: 'keamanan', tanya: 'Seseorang di Telegram mengaku admin bursa dan meminta seed phrase Anda untuk "verifikasi". Apa yang tepat?',
  pilihan: ['Tolak — pihak yang sah tidak pernah meminta seed phrase', 'Berikan, asal admin resmi', 'Berikan separuhnya saja', 'Kirim lewat email saja'],
  jelas: 'Permintaan seed phrase selalu penipuan, tanpa pengecualian.' },
{ level: 'keamanan', tanya: 'Cara menyimpan seed phrase yang paling aman adalah…',
  pilihan: ['Ditulis di kertas atau pelat logam, disimpan offline di tempat aman', 'Difoto dan disimpan di galeri HP', 'Disimpan di Google Drive', 'Dikirim ke diri sendiri lewat WhatsApp'],
  jelas: 'Semua yang tersambung ke internet bisa bocor: cloud diretas, HP hilang, aplikasi berbahaya membaca galeri.' },
{ level: 'keamanan', tanya: 'Apa beda hot wallet dan cold wallet?',
  pilihan: ['Hot wallet tersambung ke internet (praktis, lebih rawan); cold wallet menyimpan kunci offline (lebih aman untuk jangka panjang)', 'Hot wallet untuk koin mahal, cold untuk koin murah', 'Cold wallet hanya untuk Bitcoin', 'Tidak ada bedanya'],
  jelas: 'Pola umum: dana harian di hot wallet, simpanan jangka panjang di dompet hardware.' },
{ level: 'keamanan', tanya: '"Not your keys, not your coins" artinya…',
  pilihan: ['Kalau kunci privat dipegang pihak lain (misalnya bursa), aset itu pada praktiknya dalam kendali mereka', 'Koin tanpa kunci tidak bisa dijual', 'Hanya pemilik rumah yang boleh membeli crypto', 'Kunci privat bisa diganti lewat email'],
  jelas: 'Saldo di bursa adalah janji bursa. Saat FTX bangkrut (November 2022), saldo nasabah tidak bisa ditarik.' },
{ level: 'keamanan', tanya: 'Situs airdrop meminta Anda menyetujui ("approve") akses tak terbatas ke semua token. Itu tanda…',
  pilihan: ['Kemungkinan besar penguras dompet (drainer)', 'Prosedur normal klaim airdrop', 'Verifikasi KYC', 'Cara situs menghitung poin'],
  jelas: 'Approve memberi izin sebuah kontrak memindahkan token Anda. Periksa dan cabut izin lama secara berkala lewat alat seperti revoke.cash.' },
{ level: 'keamanan', tanya: 'Penipu mengirim transaksi senilai nol dari alamat yang awal dan akhirnya mirip alamat teman Anda. Namanya…',
  pilihan: ['Address poisoning — berharap Anda menyalin alamat palsu dari riwayat transaksi', 'Airdrop resmi', 'Staking otomatis', 'Pengembalian dana'],
  jelas: 'Selalu periksa seluruh alamat, bukan hanya beberapa karakter awal dan akhir, dan kirim uji coba kecil untuk jumlah besar.' },
{ level: 'keamanan', tanya: 'Dompet multisig adalah dompet yang…',
  pilihan: ['Butuh beberapa tanda tangan dari kunci berbeda (misalnya 2 dari 3) sebelum dana bisa dipindahkan', 'Bisa menyimpan banyak jenis koin', 'Dipakai banyak orang tanpa kunci', 'Otomatis menggandakan saldo'],
  jelas: 'Satu kunci bocor tidak cukup untuk mencuri dana. Treasury proyek yang dijaga multisig anonim tetap perlu dicatat sebagai risiko di dossier.' },
{ level: 'keamanan', tanya: 'Rug pull adalah…',
  pilihan: ['Pengembang menarik likuiditas atau dana proyek lalu menghilang', 'Koreksi pasar biasa', 'Delisting karena volume kecil', 'Jeda jaringan untuk pembaruan'],
  jelas: 'Menurut Akademi Crypto, sebagian sangat besar koin baru di DEX berakhir rug pull. Tidak bisa dihindari sepenuhnya, tapi bisa diantisipasi.',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'keamanan', tanya: 'Token "honeypot" adalah token yang…',
  pilihan: ['Bisa dibeli tetapi kontraknya mencegah Anda menjualnya', 'Dijamin madu sungguhan', 'Bisa dijual kapan saja tanpa batasan', 'Gratis dibagikan'],
  jelas: 'Grafiknya terlihat naik terus karena tidak ada yang bisa menjual. Periksa kontrak dengan alat pemindai token sebelum membeli koin baru.' },
{ level: 'keamanan', tanya: 'Sebelum membeli koin baru di DEX, kenapa perlu memeriksa sebaran pemegangnya (misalnya lewat Bubblemaps)?',
  pilihan: ['Kalau satu dompet memegang lebih dari ±10% suplai, atau banyak dompet kecil saling terhubung, satu pihak bisa menjatuhkan harga', 'Untuk mencari teman', 'Karena diwajibkan bursa', 'Supaya transaksi lebih murah'],
  jelas: 'Dominasi satu pemegang = satu tombol jual yang bisa meruntuhkan harga. Dompet-dompet kecil yang saling bertransaksi sering dimiliki satu orang. Pengecualian yang wajar: pool likuiditas, alamat burn, kontrak vesting, dan dompet bursa.',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'keamanan', tanya: 'Sebuah proyek sudah diaudit firma keamanan. Artinya…',
  pilihan: ['Risikonya berkurang, tetapi tidak nol — audit bisa melewatkan celah, dan kode bisa diubah setelah audit', 'Dijamin 100% aman', 'Dana dijamin pemerintah', 'Tokennya pasti naik'],
  jelas: 'Banyak protokol yang sudah diaudit tetap diretas. Audit adalah satu lapis perlindungan, bukan garansi.' },
{ level: 'keamanan', tanya: 'Kenapa server Discord atau akun X proyek crypto sering diretas penipu?',
  pilihan: ['Untuk menyebar tautan phishing yang terlihat resmi, misalnya "klaim airdrop" palsu', 'Untuk menambang koin', 'Untuk mempercepat blockchain', 'Untuk membayar pajak'],
  jelas: 'Discord Renzo misalnya diretas Juli 2024 untuk menyebar tautan phishing. Pengumuman resmi pun perlu dicek silang lewat kanal lain.' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 7 — STABLECOIN & BURSA
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'stablecoin', tanya: 'Apa itu stablecoin?',
  pilihan: ['Token yang nilainya dipatok ke aset lain, umumnya dolar AS', 'Koin yang harganya dijamin pemerintah', 'Koin apa pun yang kapitalisasinya besar', 'Token khusus staking'],
  jelas: 'Patokan bisa lepas (depeg) kalau cadangannya diragukan — stabil bukan berarti tanpa risiko.' },
{ level: 'stablecoin', tanya: 'Stablecoin berjamin dolar pertama yang mendominasi bursa, diluncurkan tahun 2014, adalah…',
  pilihan: ['Tether (USDT)', 'USDC', 'DAI', 'TerraUSD'],
  jelas: 'Urutannya: USDT (2014) → DAI dari MakerDAO (2017, stablecoin terdesentralisasi pertama yang dipakai luas) → USDC dari Circle (2018).',
  sumber: 'Delphi Digital via Akademi Crypto, Juni 2025' },
{ level: 'stablecoin', tanya: 'TerraUSD (UST) runtuh pada Mei 2022 karena…',
  pilihan: ['Stablecoin algoritmik — patokannya terutama dijaga mekanisme cetak-bakar token LUNA, bukan cadangan dolar penuh', 'Bank penyimpan cadangannya bangkrut', 'Diretas lewat seed phrase pendirinya', 'Dilarang pemerintah AS'],
  jelas: 'Saat kepercayaan hilang, pencetakan LUNA untuk menebus UST justru menghancurkan keduanya. Cadangan Bitcoin yang sempat dikumpulkan untuk membela patokan pun habis. Keruntuhan ini memicu gelombang kebangkrutan di industri tahun 2022.' },
{ level: 'stablecoin', tanya: 'USDC sempat lepas dari patokan 1 dolar pada Maret 2023 karena…',
  pilihan: ['Sebagian cadangannya tertahan di Silicon Valley Bank yang bangkrut', 'Kodenya diretas', 'Circle mencetak terlalu banyak', 'Harga Bitcoin jatuh'],
  jelas: 'Patokan kembali setelah dana nasabah SVB dijamin. Pelajarannya: stablecoin berjamin kas tetap bergantung pada bank tempat kasnya disimpan.' },
{ level: 'stablecoin', tanya: 'Dari mana penerbit stablecoin seperti Circle dan Tether mendapat pendapatan terbesarnya?',
  pilihan: ['Bunga dari cadangan yang ditaruh di obligasi pemerintah AS jangka pendek (T-bills)', 'Biaya transfer dari pengguna', 'Iklan', 'Menjual data pengguna'],
  jelas: 'Pemegang stablecoin umumnya tidak menerima bunga itu secara langsung. Bahkan chain seperti Solana dan BSC "membocorkan" nilai: bunga cadangan stablecoin di chain mereka lebih besar dari fee jaringannya sendiri.',
  sumber: 'Delphi Digital via Akademi Crypto, Oktober 2025' },
{ level: 'stablecoin', tanya: 'GENIUS Act yang disahkan di AS pada 2025 mengatur…',
  pilihan: ['Penerbitan stablecoin pembayaran — cadangan, lisensi, dan pengawasan', 'Pajak penambangan Bitcoin', 'Larangan total crypto', 'Harga ETF'],
  jelas: 'Kejelasan aturan ini ikut mendorong kapitalisasi stablecoin menembus $300 miliar pada 2025.',
  sumber: 'Messari via Akademi Crypto, 2025–2026' },
{ level: 'stablecoin', tanya: 'Di pasar P2P bursa, USDT diperdagangkan dengan premi tertinggi (±13–15% di atas kurs resmi) di negara seperti Rusia dan Nigeria. Artinya…',
  pilihan: ['Permintaan dolar digital sangat tinggi di ekonomi yang mata uangnya tertekan', 'USDT palsu', 'Bursa menipu pembeli', 'Harga Bitcoin naik'],
  jelas: 'Stablecoin menjadi jalan keluar dari inflasi dan kontrol modal — salah satu kegunaan crypto yang paling nyata.',
  sumber: 'Messari via Akademi Crypto, Agustus 2025' },
{ level: 'stablecoin', tanya: 'Apa beda utama DEX dengan bursa terpusat (CEX)?',
  pilihan: ['Di DEX penukaran lewat smart contract dan dana tetap di dompet Anda; di CEX dana dititipkan ke perusahaan', 'DEX selalu lebih murah', 'DEX diawasi OJK', 'DEX hanya menjual Bitcoin'],
  jelas: 'Risikonya berpindah: di CEX risiko bursanya bangkrut; di DEX risiko kontrak diretas dan token palsu.' },
{ level: 'stablecoin', tanya: 'Order book dan AMM adalah dua cara bursa mempertemukan pembeli dan penjual. Bedanya?',
  pilihan: ['Order book mencocokkan pesanan beli dan jual; AMM memakai pool token dan rumus untuk menentukan harga', 'Order book hanya untuk saham', 'AMM hanya untuk Bitcoin', 'Tidak ada bedanya'],
  jelas: 'Binance dan Hyperliquid memakai order book; Uniswap memakai AMM. Belakangan AMM "prop" di Solana bahkan menawarkan biaya lebih murah dari CEX besar.',
  sumber: 'Messari via Akademi Crypto, Mei 2026' },
{ level: 'stablecoin', tanya: 'Market cap sebuah token dihitung dengan cara…',
  pilihan: ['Harga × jumlah token yang beredar', 'Harga × jumlah token maksimum', 'Total dana investor', 'Volume 24 jam × harga'],
  jelas: 'Kalau yang dipakai suplai maksimum, hasilnya FDV. Selisih keduanya menunjukkan berapa token yang masih akan dilepas.' },
{ level: 'stablecoin', tanya: 'Slippage adalah…',
  pilihan: ['Selisih antara harga yang diharapkan dan harga yang benar-benar didapat saat transaksi dieksekusi', 'Biaya langganan bursa', 'Pajak transaksi', 'Nama bot trading'],
  jelas: 'Makin tipis likuiditas dan makin besar order, makin besar slippage. Toleransi slippage yang terlalu longgar juga mengundang serangan sandwich.' },
{ level: 'stablecoin', tanya: 'Menurut patokan Akademi Crypto untuk memecoin, rasio market cap terhadap likuiditas yang sehat untuk koin kecil (±$10 juta) adalah sekitar…',
  pilihan: ['5 : 1 (minimal ±$2 juta likuiditas)', '1.000 : 1', '1 : 5', 'Tidak perlu likuiditas'],
  jelas: 'Patokan mereka: kecil 5:1, menengah 10:1, besar 20:1. Rasio terlalu tinggi berarti kapitalisasinya "kosong" — sulit masuk dan keluar tanpa menggeser harga.',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'stablecoin', tanya: 'Sepanjang 2025 ada 652 listing token baru di lima bursa besar (Binance, Bybit, Coinbase, Kraken, Gate). Bagaimana nasib yang membeli di hari pertama?',
  pilihan: ['Mayoritas rugi: hanya ±12% yang untung, median −82%', 'Hampir semua untung besar', 'Rata-rata naik 10 kali', 'Harga tidak bergerak'],
  jelas: 'Membeli $1.000 di setiap listing hari pertama akan menghabiskan sekitar setengah modal. Euforia listing bukan strategi.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2026' },
{ level: 'stablecoin', tanya: 'KYC di bursa terpusat adalah…',
  pilihan: ['Verifikasi identitas nasabah (Know Your Customer) sebagai bagian aturan anti pencucian uang', 'Nama koin baru', 'Fitur staking', 'Jenis dompet'],
  jelas: 'Di AS, aturan anti pencucian uang berakar pada Bank Secrecy Act (1970); sejak 2018 Uni Eropa memasukkan penyedia aset crypto ke dalamnya.',
  sumber: 'Messari via Akademi Crypto, Juli 2025' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 8 — DEFI: CARA KERJANYA
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'defi', tanya: 'TVL (total value locked) mengukur…',
  pilihan: ['Nilai aset yang disetor ke sebuah protokol DeFi', 'Pendapatan tahunan protokol', 'Jumlah pengguna harian', 'Harga token protokol'],
  jelas: 'TVL besar belum tentu sehat. Di lending, yang lebih penting adalah berapa yang benar-benar dipinjam (modul 3).', modul: 3 },
{ level: 'defi', tanya: 'Kenapa pinjaman di Aave atau Compound harus "overcollateralized"?',
  pilihan: ['Karena tidak ada verifikasi identitas; jaminan yang lebih besar dari pinjaman adalah satu-satunya pengaman pemberi pinjaman', 'Karena diwajibkan bank sentral', 'Supaya bunganya nol', 'Karena crypto tidak bisa dipinjam'],
  jelas: 'Pinjaman tanpa jaminan generasi pertama (TrueFi, Goldfinch, Centrifuge) banyak gagal karena lemah di transparansi, insentif, dan penegakan.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2025' },
{ level: 'defi', tanya: 'Apa yang terjadi saat nilai jaminan peminjam jatuh di bawah batas aman?',
  pilihan: ['Posisi dilikuidasi: jaminan dijual otomatis untuk melunasi utang, biasanya dengan denda', 'Utang dihapus', 'Bunga menjadi nol', 'Pinjaman dibekukan selamanya'],
  jelas: 'Likuidasi massal saat pasar jatuh bisa memperparah penurunan — efek domino yang coba diredam desain lending baru.' },
{ level: 'defi', tanya: 'Penyedia likuiditas (LP) di AMM mendapat penghasilan dari…',
  pilihan: ['Bagian dari fee setiap swap di pool tempat mereka menyetor', 'Gaji dari bursa', 'Bunga bank', 'Iklan'],
  jelas: 'Sebagai gantinya, LP menanggung risiko impermanent loss.' },
{ level: 'defi', tanya: 'Impermanent loss adalah…',
  pilihan: ['Kerugian LP dibanding sekadar memegang token, yang muncul saat harga dua token di pool bergerak menjauh', 'Kehilangan kunci privat', 'Biaya gas', 'Pajak DeFi'],
  jelas: 'Disebut "impermanent" karena hilang kalau harga kembali ke posisi awal. Kalau LP menarik dana saat harga sudah berubah, kerugiannya menjadi nyata.' },
{ level: 'defi', tanya: 'Yield farming / liquidity mining adalah…',
  pilihan: ['Protokol membagikan token barunya kepada penyetor likuiditas sebagai insentif tambahan', 'Menanam pohon sungguhan', 'Menambang Bitcoin', 'Membeli saham petani'],
  jelas: 'Imbal hasil tinggi dari emisi token sering hanya pengenceran yang dibagikan — begitu insentif berhenti, dana pergi (modul 4).', modul: 4 },
{ level: 'defi', tanya: 'Model "ve-token" (veCRV di Curve, veAERO di Aerodrome) bekerja dengan cara…',
  pilihan: ['Token dikunci hingga bertahun-tahun untuk mendapat hak suara atas emisi dan bagian fee', 'Token dibakar setiap hari', 'Token dibagikan gratis ke semua orang', 'Token dijual otomatis setiap bulan'],
  jelas: 'Di Aerodrome, pengunci veAERO menerima fee dan "bribe" dari proyek yang ingin emisinya diarahkan ke pool mereka. Risikonya inflasi dari emisi.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2026' },
{ level: 'defi', tanya: 'MEV (maximal extractable value) adalah…',
  pilihan: ['Keuntungan yang bisa diambil pihak yang mengatur urutan transaksi dalam blok, misalnya menyelipkan transaksi sebelum dan sesudah milik Anda', 'Pajak resmi blockchain', 'Nama token', 'Bonus staking'],
  jelas: 'Bentuk paling umum adalah sandwich attack. Chain dengan satu proposer blok memberi kuasa besar atas urutan; chain multi-proposer mengurangi, tapi tidak menghapusnya.',
  sumber: 'Messari via Akademi Crypto, Juli 2026' },
{ level: 'defi', tanya: 'Dalam sandwich attack, bot melakukan…',
  pilihan: ['Membeli tepat sebelum swap Anda, membiarkan Anda membeli di harga lebih mahal, lalu langsung menjual setelahnya', 'Mencuri kunci privat Anda', 'Menghapus transaksi Anda', 'Mengirim Anda token gratis'],
  jelas: 'Toleransi slippage yang ketat dan RPC privat (anti-MEV) membantu mengurangi risiko ini.' },
{ level: 'defi', tanya: 'Flash loan adalah…',
  pilihan: ['Pinjaman tanpa jaminan yang harus dipinjam dan dilunasi dalam satu transaksi yang sama — kalau tidak lunas, seluruh transaksi batal', 'Pinjaman kilat dari bank', 'Pinjaman untuk membeli lampu', 'Pinjaman dengan bunga nol selama setahun'],
  jelas: 'Dipakai untuk arbitrase dan likuidasi — tetapi juga sering jadi alat serangan manipulasi harga oracle.' },
{ level: 'defi', tanya: 'Kenapa bridge lintas chain sering menjadi sasaran peretasan terbesar?',
  pilihan: ['Bridge mengunci aset dalam jumlah sangat besar di satu tempat, dan keamanannya sering bergantung pada sedikit kunci', 'Karena bridge tidak memakai kode', 'Karena bridge dimiliki pemerintah', 'Karena bridge tidak menyimpan aset'],
  jelas: 'Contoh: Ronin (2022) kehilangan ±$600 juta setelah kunci validatornya dibobol. Aset "wrapped" di chain tujuan hanya bernilai selama bridge-nya aman.' },
{ level: 'defi', tanya: 'Perpetual futures berbeda dari futures biasa karena…',
  pilihan: ['Tidak punya tanggal jatuh tempo; harganya dijaga dekat harga spot lewat funding rate', 'Hanya bisa naik', 'Tidak memakai margin', 'Hanya untuk saham'],
  jelas: 'Harga oracle dari banyak bursa membentuk "mark price" yang dipakai untuk menghitung margin, likuidasi, dan untung-rugi.',
  sumber: 'Messari via Akademi Crypto, Agustus 2026' },
{ level: 'defi', tanya: 'Saat harga perpetual lebih mahal dari harga spot, funding rate positif. Artinya…',
  pilihan: ['Pemegang posisi long membayar pemegang posisi short secara berkala', 'Short membayar long', 'Bursa membayar semua trader', 'Tidak ada yang membayar'],
  jelas: 'Insentif ini menarik harga perpetual kembali ke spot. Funding ekstrem adalah salah satu sinyal narasi sedang di fase distribusi (modul 9).', modul: 9 },
{ level: 'defi', tanya: 'Leverage 10× pada posisi long berarti…',
  pilihan: ['Harga turun sekitar 10% saja sudah cukup untuk menghapus seluruh margin (likuidasi)', 'Untung dijamin 10 kali', 'Rugi maksimal 10%', 'Posisi aman dari likuidasi'],
  jelas: 'Itu sebabnya Akademi Crypto menyarankan pemula yang mengenal crypto kurang dari setahun tidak memakai leverage.',
  sumber: 'Akademi Crypto, Februari 2025' },
{ level: 'defi', tanya: 'Di Polymarket, 1 USDC dipecah menjadi 1 token YES dan 1 token NO. Kalau token YES diperdagangkan di $0,70, artinya…',
  pilihan: ['Pasar menilai peluang peristiwa itu terjadi sekitar 70%; kalau benar terjadi, YES ditebus $1', 'Tiket masuk seharga 70 sen', 'Biaya transaksi 70%', 'Peristiwa sudah pasti terjadi'],
  jelas: 'Setelah hasilnya diumumkan, token yang benar bernilai $1 dan yang salah $0.',
  sumber: 'Messari via Akademi Crypto, November 2025' },
{ level: 'defi', tanya: 'Era "fee switch" DeFi 2024–2026 ditandai dengan…',
  pilihan: ['Protokol seperti Hyperliquid, Aave, Uniswap, Jupiter, dan Pendle mulai mengalirkan pendapatan ke pemegang token lewat buyback, burn, atau bagi hasil', 'Semua DeFi berhenti memungut fee', 'Fee dipindah ke bank', 'Token governance dilarang'],
  jelas: 'Sebelumnya banyak protokol menahan diri, antara lain karena kekhawatiran tokennya dianggap sekuritas. Perubahan regulasi membuka jalan.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2026' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 9 — MEMBACA TOKEN (modul 1–5)
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'token', modul: 1, tanya: 'Menurut kerangka "Langkah −1", analisis sebuah token dimulai dari…',
  pilihan: ['Kebutuhan — siapa yang butuh protokol ini dan seberapa besar', 'Grafik harga 90 hari', 'Jumlah pengikut di X', 'Halaman pertama whitepaper'],
  jelas: 'Token punya nilai kalau ada kebutuhan yang dipenuhi protokolnya dan tokennya memang perlu ada untuk memenuhinya.' },
{ level: 'token', modul: 1, tanya: 'Memilih koin karena sedang ramai, lalu mencari-cari alasan untuk membelinya, disebut…',
  pilihan: ['Token-driven', 'Thesis-driven', 'Value investing', 'Dollar cost averaging'],
  jelas: 'Thesis-driven memilih aset karena ia mendukung tesis. Token-driven kebalikannya.' },
{ level: 'token', tanya: 'Menurut pohon klasifikasi token (Nansen), token yang tidak punya nilai intrinsik sama sekali tergolong…',
  pilihan: ['Memecoin — murni alat spekulasi', 'Security token', 'Asset-backed token', 'Network token'],
  jelas: 'Yang punya nilai dibedakan lagi: dikendalikan perusahaan (security, company-backed, arcade token) atau tidak (network token, collectible, asset-backed).',
  sumber: 'Nansen via Akademi Crypto, Maret 2025' },
{ level: 'token', modul: 2, tanya: 'Sebuah bursa perpetual terdesentralisasi. Siapa pesaing sebenarnya?',
  pilihan: ['Bursa perpetual lain', 'Bitcoin', 'Semua koin 100 besar', 'Bank konvensional'],
  jelas: 'Pesaing sejati ada di lapisan yang sama.' },
{ level: 'token', modul: 3, tanya: 'Protokol lending punya TVL besar, tetapi pinjaman aktifnya kecil. Bacaan yang tepat?',
  pilihan: ['Jantungnya lemah — TVL itu sebagian besar uang parkir', 'Sangat sehat karena TVL besar', 'Harganya pasti naik', 'Tidak bisa dinilai'],
  jelas: 'Jantung lending adalah pinjaman aktif dan selisih bunganya, bukan TVL.' },
{ level: 'token', tanya: 'Sebuah token RWA punya kapitalisasi ±$8 miliar tetapi TVL-nya hanya ±$4 juta, ditambah unlock ±12% suplai beredar dalam enam bulan. Bacaannya?',
  pilihan: ['Red flag: valuasi jauh melampaui fundamental, dan tekanan jual terjadwal besar', 'Sangat murah', 'Sehat karena kapitalisasinya besar', 'Tidak relevan'],
  jelas: 'Ini kasus Mantra (OM) yang dibahas April 2025. Bandingkan dengan Ondo yang saat itu punya TVL ±$1 miliar untuk kapitalisasi ±$5 miliar.',
  sumber: 'Insight Unlock via Akademi Crypto, April 2025' },
{ level: 'token', modul: 4, tanya: 'Dari fee, pendapatan protokol, dan holders revenue — mana yang benar-benar sampai ke pemegang token?',
  pilihan: ['Holders revenue: buyback, bagi fee, atau burn dari pendapatan nyata', 'Fee total pengguna', 'TVL', 'Volume'],
  jelas: 'Hanya yang mengalir ke pemegang token yang dihitung sebagai arus kas di rumus nilai intrinsik.' },
{ level: 'token', modul: 4, tanya: 'Staking yield 12% yang dibayar dari pencetakan token baru adalah…',
  pilihan: ['Pengenceran yang dibagikan, bukan arus kas', 'Arus kas murni', 'Bunga bebas risiko', 'Pendapatan protokol'],
  jelas: 'Yang tidak ikut staking kehilangan porsi; yang ikut hanya bertahan di tempat.' },
{ level: 'token', modul: 4, tanya: 'Arus kas ke pemegang $60 juta per tahun, r = 20%, g = 0. Berapa nilai intrinsiknya?',
  pilihan: ['$300 juta', '$1,2 miliar', '$72 juta', '$600 juta'],
  jelas: 'V = CF × (1 + g) ÷ (r − g) = 60 ÷ 0,20 = $300 juta.' },
{ level: 'token', modul: 4, tanya: 'Rasio FDV ÷ nilai intrinsik = 12. Artinya…',
  pilihan: ['Yang dibayar pasar adalah narasi, bukan arus kas', 'Harganya di bawah nilai', 'Wajar untuk aset tumbuh', 'Pasti turun besok'],
  jelas: 'Patokan: ≤ 1 di bawah nilai, 1–3 wajar, 3–10 memuat pertumbuhan besar, > 10 narasi.' },
{ level: 'token', tanya: 'Kenapa token banyak jaringan layer 2 kinerjanya buruk walau jaringannya ramai?',
  pilihan: ['Fee jaringan tidak otomatis mengalir ke token; token sering hanya dipakai untuk voting', 'Karena L2 dilarang', 'Karena L2 tidak punya pengguna', 'Karena L2 memakai Proof of Work'],
  jelas: 'Data Delphi (2026): dua tahun setelah peluncuran, token L2 termasuk kelompok terburuk, sementara token bursa yang pendapatannya jelas tampil jauh lebih baik.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2026' },
{ level: 'token', modul: 5, tanya: 'FDV (fully diluted valuation) dihitung dari…',
  pilihan: ['Harga × seluruh suplai, termasuk yang belum dilepas', 'Harga × suplai beredar', 'TVL × harga', 'Pendapatan × 12'],
  jelas: 'Pembeli hari ini ikut menanggung dilusi dari token yang dilepas besok.' },
{ level: 'token', modul: 5, tanya: 'Kombinasi mana yang cenderung sulit naik?',
  pilihan: ['FDV tinggi + float rendah', 'FDV rendah + float tinggi', 'FDV sama dengan market cap', 'Float 100%'],
  jelas: 'Persepsi valuasi terlalu tinggi, ditambah likuiditas tipis yang membuat setiap penjualan menggeser harga jauh.' },
{ level: 'token', modul: 5, tanya: 'Batas peringatan unlock di modul 5 adalah…',
  pilihan: ['Lebih dari 5% suplai beredar dilepas dalam 90 hari', 'Lebih dari 50% setahun', 'Unlock berapa pun aman', 'Lebih dari 1% dalam lima tahun'],
  jelas: 'Riset 2026 atas 400+ unlock pada 33 token: rata-rata token tertinggal ±7% dari Bitcoin di sekitar unlock, dan efeknya menumpuk bila unlock terjadi tiap bulan.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2026' },
{ level: 'token', tanya: 'Dalam kategori standar alokasi token, kelompok mana yang biasanya TIDAK terikat masa vesting?',
  pilihan: ['Investor publik (ICO, IDO, launchpad)', 'Tim pendiri', 'Investor privat (VC, angel)', 'Cadangan treasury'],
  jelas: 'Lima kategori standar: pendiri/tim, investor privat, investor publik, cadangan (treasury/foundation/DAO), dan komunitas (airdrop, liquidity mining, hadiah staking).',
  sumber: 'Tokenomist via Akademi Crypto, September 2025' },
{ level: 'token', modul: 5, tanya: 'Tim menerima $27 juta token dari unlock. Cara paling tepat menilai apakah mereka menjual?',
  pilihan: ['Lacak dompet penerima dan hitung berapa yang benar-benar dicairkan', 'Anggap semua pasti dijual', 'Abaikan, tim pasti jujur', 'Lihat pengikut tim di X'],
  jelas: 'Asumsi ke dua arah sama-sama malas; perilaku dompet bisa diperiksa on-chain.' },
{ level: 'token', tanya: 'Valuasi (FDV) token baru saat peluncuran sudah turun 85–96% sejak awal 2024. Apakah itu membuat token baru jadi aman dibeli?',
  pilihan: ['Belum — sebagian besar masih turun 30–80% lagi dalam 180 hari; pasar menuntut pengguna dan pendapatan nyata', 'Ya, pasti naik', 'Ya, karena sudah murah', 'Tidak ada hubungannya'],
  jelas: '"Sudah murah dibanding dulu" bukan alasan. Yang bertahan adalah proyek dengan fundamental kuat.',
  sumber: 'Delphi Digital via Akademi Crypto, Juli 2026' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 10 — SIKLUS, MAKRO & DATA ON-CHAIN (modul 6–7)
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'pasar', tanya: 'Tahap adopsi crypto menurut Akademi Crypto bergerak dari…',
  pilihan: ['Individu vs individu → individu vs institusi → institusi vs institusi → individu vs pemerintah → pemerintah vs pemerintah', 'Pemerintah dulu, baru individu', 'Bank dulu, baru bursa', 'Tidak ada urutannya'],
  jelas: 'Tahap terakhir adalah negara-negara bersaing mengadopsi teknologi dan aset crypto.',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'pasar', tanya: 'Dalam siklus bull, pola historisnya adalah…',
  pilihan: ['Bitcoin naik lebih dulu, lalu pertumbuhan berpindah ke altcoin — yang di beberapa siklus naik jauh lebih tinggi', 'Altcoin selalu naik lebih dulu', 'Semua naik bersamaan', 'Bitcoin dan altcoin tidak berhubungan'],
  jelas: 'Siklus 2015–2018: altcoin tumbuh ±990× sementara Bitcoin ±106×, tetapi baru setelah Bitcoin memimpin di fase awal. Polanya melemah: 2018–2021 altcoin 35× vs Bitcoin 23×, dan 2022–2023 justru Bitcoin yang memimpin.',
  sumber: 'Pantera Capital via Akademi Crypto, Februari 2025' },
{ level: 'pasar', modul: 6, tanya: 'Tahap kedua siklus altcoin — harga jenuh turun, pembeli belum percaya diri — disebut…',
  pilihan: ['Kapitulasi berbasis waktu', 'Banjir rilis', 'Short squeeze', 'Halving'],
  jelas: 'Banjir rilis → kapitulasi berbasis waktu → penjual di dasar terkena short squeeze.' },
{ level: 'pasar', modul: 6, tanya: 'Di tahap kapitulasi, volume naik sementara harga datar. Itu tanda…',
  pilihan: ['Akumulasi diam-diam', 'Pembeli pergi', 'Akan delisting', 'Data rusak'],
  jelas: 'Uang besar tidak mengejar harga; ia menyerap penawaran.' },
{ level: 'pasar', modul: 7, tanya: 'Rantai transmisi makro yang utama adalah…',
  pilihan: ['Berita AS → SPX → Bitcoin → altcoin', 'Berita Asia → altcoin → Bitcoin', 'Emas → Bitcoin → SPX', 'Altcoin → Bitcoin → berita AS'],
  jelas: 'Yang dipantau cukup rilis AS berbintang 2–3: FOMC, inflasi, tenaga kerja.' },
{ level: 'pasar', modul: 7, tanya: 'Rantai transmisi kedua yang dipantau Akademi Crypto adalah…',
  pilihan: ['Aliran dana ETF → Ethereum → altcoin', 'Harga minyak → Dogecoin', 'Suku bunga Jepang → NFT', 'Cuaca → penambang'],
  jelas: 'Setelah ETH berbalik positif didorong aliran ETF, altcoin cenderung mengikuti.' },
{ level: 'pasar', modul: 7, tanya: 'Transfer besar ke bursa menjelang katalis yang sudah diumumkan publik biasanya dibaca sebagai…',
  pilihan: ['Persiapan jual — "sell the news"', 'Akumulasi', 'Bursa bangkrut', 'Airdrop'],
  jelas: 'Satu variabel, dua tanda: masuk ke bursa = bersiap jual; keluar dari bursa saat harga jatuh = akumulasi.' },
{ level: 'pasar', tanya: 'Protokol riset Akademi Crypto 2025 menambahkan dua jenis riset baru di samping naratif, teknikal, dan fundamental. Apa itu?',
  pilihan: ['Riset sentimen (media sosial, Fear & Greed) dan riset on-chain (whale, arus stablecoin, aktivitas jaringan)', 'Riset astrologi dan numerologi', 'Riset desain logo', 'Riset jumlah karyawan'],
  jelas: 'Porsi 2023 mereka: naratif 50%, teknikal 30%, fundamental 20%. Tahun 2025 mereka menambahkan riset sentimen dan on-chain ke dalam protokol itu.',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'pasar', tanya: 'Mindshare sebuah proyek terus naik, tetapi harganya turun. Menurut metode mindshare/harga, itu bisa berarti…',
  pilihan: ['Proyek relatif undervalued — makin banyak dibicarakan, harganya sedang diskon', 'Proyek pasti mati', 'Proyek overvalued', 'Tidak ada artinya'],
  jelas: 'Kebalikannya — mindshare turun tapi harga naik — sering berarti kenaikan hanya ditopang segelintir pihak dan rawan berbalik.',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'pasar', tanya: 'Anda benar menebak narasi AI akan naik, tetapi token AI yang Anda pegang justru jatuh. Kesalahan ini disebut…',
  pilihan: ['"Right trend, wrong token" — arah benar, pilihan aset salah', 'Loss aversion', 'Halving', 'Rug pull'],
  jelas: 'Contoh GOAT: saat mindshare AI naik dari 31% ke 64%, kapitalisasi GOAT justru jatuh dari $1,31 miliar ke $500 juta karena pemenang baru muncul.',
  sumber: 'Messari via Akademi Crypto, Mei 2025' },
{ level: 'pasar', tanya: 'Perusahaan "crypto treasury" (misalnya Strategy/MSTR) bisa menambah Bitcoin per saham dengan menerbitkan saham biasa baru selama…',
  pilihan: ['Sahamnya diperdagangkan di atas nilai aset bersihnya (premi mNAV), sehingga menerbitkan saham baru tetap menguntungkan pemegang lama', 'Harga Bitcoin turun', 'Perusahaan tidak menerbitkan saham', 'Selamanya tanpa syarat'],
  jelas: 'Saat premi menyempit, siklus melambat — "BTC Yield" Strategy turun dari 74% (2024) ke di bawah 10% (awal 2026) dan pendanaan beralih ke saham preferen.',
  sumber: 'Messari & Delphi Digital via Akademi Crypto, 2025–2026' },
{ level: 'pasar', tanya: 'Dana pensiun 401(k) yang memuat ETF Bitcoin disebut "perpetual bid" karena…',
  pilihan: ['Potongan gaji otomatis setiap bulan menciptakan permintaan beli yang terus mengalir', 'Dana pensiun dilarang menjual', 'Harga Bitcoin dijamin naik', 'Pemerintah membeli Bitcoin'],
  jelas: 'Permintaan struktural seperti ini berbeda dari pembelian spekulatif — ia datang terus terlepas dari suasana pasar.',
  sumber: 'Delphi Digital via Akademi Crypto, November 2025' },
{ level: 'pasar', tanya: 'Kebijakan crypto global berubah dari tahun ke tahun. Urutan yang tepat adalah…',
  pilihan: ['Skeptis dan kriminalisasi (2011–2019) → "regulation by enforcement" (2021–2024) → titik balik ke arah institusionalisasi (2025)', 'Selalu mendukung sejak awal', 'Selalu melarang', 'Mendukung dulu, lalu melarang'],
  jelas: 'Titik balik 2025 ditandai pergantian pimpinan regulator dan pembentukan Strategic Bitcoin Reserve AS lewat perintah eksekutif (Maret 2025), diisi Bitcoin sitaan pemerintah.',
  sumber: 'Messari via Akademi Crypto, Januari 2026' },
{ level: 'pasar', modul: 6, tanya: 'Dua token sama-sama turun 85% dari puncak. Kenapa artinya bisa berlawanan?',
  pilihan: ['Tahap siklusnya berbeda — float dan unlock yang tersisa berbeda', 'Warna grafiknya', 'Salah satunya pasti penipuan', 'Tidak mungkin berbeda'],
  jelas: 'Yang baru rilis dengan float kecil masih menunggu unlock; yang sudah lama di bawah dengan float besar sedang di tahap 2.' },

// ═══════════════════════════════════════════════════════════════════════════
// LEVEL 11 — MENTAL, ALOKASI & TRADING NARATIF (modul 8–9)
// ═══════════════════════════════════════════════════════════════════════════
{ level: 'mental', modul: 8, tanya: 'Loss aversion adalah…',
  pilihan: ['Kerugian terasa jauh lebih sakit daripada keuntungan sebesar yang sama terasa menyenangkan', 'Takut ketinggalan', 'Suka koin murah', 'Enggan membayar fee'],
  jelas: 'Akibatnya drawdown kecil memicu keputusan besar.' },
{ level: 'mental', modul: 8, tanya: 'Beli 100 koin di $1. Turun 50%, Anda jual. Naik ke $2, Anda beli lagi dengan seluruh uang tadi. Berapa koin Anda sekarang?',
  pilihan: ['25 koin', '50 koin', '100 koin', '200 koin'],
  jelas: 'Jual di $0,50 → $50. Beli di $2 → 25 koin. Harga "sudah kembali", tiga perempat aset hilang.' },
{ level: 'mental', modul: 8, tanya: 'Break-even syndrome terjadi ketika…',
  pilihan: ['Tujuan berubah dari "menang" menjadi "yang penting balik modal"', 'Harga tidak bergerak', 'Bursa menahan dana', 'Portofolio dibagi rata'],
  jelas: 'Begitu harga kembali ke titik masuk dijual, lalu dibeli lagi lebih tinggi karena FOMO.' },
{ level: 'mental', tanya: 'Kenapa platform seperti Pump.fun membuat orang enggan mengambil untung?',
  pilihan: ['"Dopamine loop": otak lebih menikmati harapan "bagaimana kalau naik 10×" daripada untung yang sudah ada', 'Karena dilarang menjual', 'Karena fee jual sangat mahal', 'Karena koinnya selalu naik'],
  jelas: 'Menyadari bias ini adalah langkah pertama untuk punya rencana ambil untung sebelum masuk.',
  sumber: 'Messari via Akademi Crypto, Oktober 2025' },
{ level: 'mental', tanya: 'Menurut Akademi Crypto, trader sukses menghabiskan waktunya…',
  pilihan: ['Sekitar 80–90% untuk riset, sisanya untuk eksekusi; banyak yang hanya aktif 2–3 bulan dalam setahun', 'Membuka posisi setiap hari', 'Menggambar pola grafik sepanjang hari', 'Mengikuti sinyal grup'],
  jelas: 'Pemula melakukan kebalikannya: sibuk keluar-masuk pasar, sedikit waktu untuk memahami apa yang akan terjadi.',
  sumber: 'Akademi Crypto, Agustus 2024 & Februari 2025' },
{ level: 'mental', tanya: 'Tiga "modal" yang dibutuhkan untuk trading crypto menurut Akademi Crypto adalah…',
  pilihan: ['Waktu, energi, dan kapital', 'HP, laptop, dan internet', 'Keberanian, keberuntungan, dan sinyal', 'Teman, grup, dan influencer'],
  jelas: 'Ketiganya harus ada — uang saja tidak cukup. Aturan utama mereka: jangan kehilangan uang.',
  sumber: 'Akademi Crypto, Februari 2025' },
{ level: 'mental', tanya: 'Barbell strategy dalam crypto berarti…',
  pilihan: ['Sekitar 70% sangat konservatif (akumulasi Bitcoin), 30% agresif (altcoin dan aktivitas berisiko)', '50% emas, 50% saham', 'Semua di satu koin', 'Semua di stablecoin'],
  jelas: 'Dua ujung ekstrem, tanpa bagian tengah yang "setengah-setengah".',
  sumber: 'Akademi Crypto, Januari 2025' },
{ level: 'mental', tanya: 'Aturan "1%" Akademi Crypto untuk aset berisiko artinya…',
  pilihan: ['Setiap taruhan altcoin atau memecoin hanya mempertaruhkan sekitar 1% modal, sehingga satu kekalahan tidak merusak portofolio', 'Untung minimal 1% sehari', 'Membeli 1% dari suplai koin', 'Menjual 1% setiap hari'],
  jelas: 'Terlalu banyak pilihan altcoin menjebak orang dalam "paradox of choice"; ukuran kecil membuat kesalahan bisa ditanggung. Bedakan: 1% adalah modal yang siap hilang per taruhan (risiko), sedangkan batas 3–5% adalah ukuran maksimum satu posisi.',
  sumber: 'Akademi Crypto, Februari 2025' },
{ level: 'mental', tanya: 'Dalam tiga skenario alokasi Akademi Crypto (Nov 2025), skenario konservatif menjelang bear market adalah…',
  pilihan: ['Bitcoin 30%, stablecoin 60%, trading harian 10% dengan risiko 1% per trade', 'Altcoin 100%', 'Bitcoin 0%, memecoin 100%', 'Stablecoin 0%, leverage 100%'],
  jelas: 'Skenario moderat: Bitcoin 50%, stablecoin 30%, trading 20%. Agresif: Bitcoin 70%, trading 30%. Di bear market, altcoin sebaiknya tidak ditahan di spot.',
  sumber: 'Akademi Crypto, kanal alokasi-portofolio, November 2025' },
{ level: 'mental', tanya: 'Aset Anda naik 100%. Agar modal awal kembali utuh dan sisanya tetap berjalan (moonbag), berapa porsi yang dijual?',
  pilihan: ['50%', '25%', '10%', '100%'],
  jelas: 'Posisi bernilai 2× modal; menjual separuhnya = 1× modal kembali. Menjual 25% hanya mengembalikan separuh modal.',
  sumber: 'Akademi Crypto, Februari 2025', modul: 9 },
{ level: 'mental', tanya: 'Kenapa Akademi Crypto menyarankan membeli bertahap (multiple entry), bukan sekali masuk?',
  pilihan: ['Dasar dan puncak tidak bisa ditebak karena terlalu banyak variabel — internal (unlock, developer, peretasan) maupun eksternal (Bitcoin, makro, geopolitik)', 'Supaya fee lebih mahal', 'Karena bursa membatasi', 'Supaya terlihat sibuk'],
  jelas: '"One shoot one kill is only for gamblers." Smart money masuk bertahap dan keluar bertahap — bahkan cut loss pun bertahap.',
  sumber: 'Akademi Crypto, Mei 2024' },
{ level: 'mental', modul: 9, tanya: 'Dalam skor naratif tujuh kriteria, dua kriteria berbobot terbesar adalah…',
  pilihan: ['Kekuatan katalis dan tokenomics (masing-masing 20%)', 'Likuiditas dan timing', 'Tim dan revenue', 'TAM dan likuiditas'],
  jelas: 'Katalis 20, tokenomics 20, TAM 15, tim & VC 15, likuiditas 10, timing 10, revenue 10.' },
{ level: 'mental', modul: 9, tanya: 'Berapa dari enam sinyal fase distribusi yang harus menyala sebelum narasi dianggap kemungkinan besar di puncak?',
  pilihan: ['Tiga atau lebih', 'Satu saja', 'Keenamnya', 'Tidak ada patokan'],
  jelas: 'Funding ekstrem, OI di puncak, listing tier-1, media mainstream, saturasi influencer, Google Trends di puncak.' },
{ level: 'mental', modul: 9, tanya: 'Dalam kerangka core-satellite, porsi maksimum satu altcoin adalah…',
  pilihan: ['5% portofolio', '50%', '100% kalau yakin', 'Minimal 20%'],
  jelas: 'Disclaimer Akademi Crypto bahkan lebih ketat: satu altcoin maksimal 3%, dan kas minimal 10%. Ini batas ukuran posisi — berbeda dari aturan 1%, yaitu besar modal yang dipertaruhkan per trade.' },
{ level: 'mental', modul: 9, tanya: 'Mana yang termasuk lima aturan invalidasi tesis narasi?',
  pilihan: ['Mindshare turun beberapa minggu berturut-turut', 'Harga naik 5% sehari', 'Ada influencer baru', 'Masuk daftar trending'],
  jelas: 'Katalis gagal, mindshare turun, developer pergi, fase decay, struktur harga rusak di level kunci.' },
{ level: 'mental', tanya: 'Dana seperti apa yang pantas dipakai untuk crypto?',
  pilihan: ['Dana dingin — uang yang tidak dibutuhkan dalam waktu dekat dan siap menanggung penurunan besar', 'Dana darurat keluarga', 'Uang pinjaman', 'Uang kuliah bulan depan'],
  jelas: 'Aset crypto bisa turun 80% dalam setahun. Uang yang harus tersedia minggu depan akan memaksa Anda menjual di waktu terburuk.' },
];
